services:
  - type: web
    name: image-classifier-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: bash backend/start.sh
    plan: free
    runtime: python
    region: oregon
    branch: main
    autoDeploy: true
    rootDir: .